---
- name: Give the tomcat group ownership over the entire installation directory
  file:
     path: /opt/tomcat
     group: tomcat 
     recurse: yes
     state: directory
- name: give the tomcat group read access to the conf directory
  file:
     path: /opt/tomcat/conf
     recurse: yes
     mode: g+r
     state: directory

- name: give the tomcat group execute access to the conf directory
  file:
    path: /opt/tomcat/conf
    mode: g+x
    state: directory

-  name: Make the tomcat user the owner of the webapps
   file: 
     path: /opt/tomcat/webapps
     recurse: yes
     owner: tomcat
     state: directory
-  name: Make the tomcat user the owner of the work
   file: 
     path: /opt/tomcat/work
     recurse: yes
     owner: tomcat
     state: directory

-  name: Make the tomcat user the owner of the temp
   file: 
     path: /opt/tomcat/temp
     recurse: yes
     owner: tomcat
     state: directory
-  name: Make the tomcat user the owner of the logs
   file: 
     path: /opt/tomcat/logs
     recurse: yes
     owner: tomcat
     state: directory



