---
# tasks file for mytom8onubuntu16role

- include_tasks: installjava.yml
- include_tasks: TomcatUser.yml
- include_tasks: InstallTomcat.yml
- include_tasks: UpdatePermissions.yml
- include_tasks: ServiceFile.yml
- include_tasks: starttomcat.yml
- include_tasks: TomcatWebInterface.yml
- include_tasks: restarttomcat.yml
- include_tasks: deployjavaapplication.yml
- include_tasks: restarttomcat.yml