---
- name : create group
  group:
     name: tomcat 
     state: present


- name: create user
  user: 
     name: tomcat
     shell: /bin/false 
     group: tomcat
     home: /opt/tomcat
     state: present